src/payment/urls.py
from django.urls import path
from payment import views

app_name = "payments"
urlpatterns = [
    path('payment/<int:id>', views.payment, name='payment'),
]

src/tshirt/urls.py
from django.urls import path
from tshirt import views


urlpatterns = [
  path('tshirt/<int:page>', views.index, name='tshirts'),
  path('', views.index, name='tshirt'),
  path('tshirt/selection/<int:id>', views.selectedTshirt, name='selectedTshirt')
]

src/vendingmachine/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from tshirt.api import TshirtApiView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', TshirtApiView.as_view()),
    path('', include('tshirt.urls')),
    path('', include('payment.urls', namespace='payments'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.IMG_URL,
                          document_root=settings.IMG_ROOT)

src/payment/models.py
from django.db import models

class Payment(models.Model):
  name = models.CharField(max_length=30, default="PIX", blank=True)

src/sale/models.py
from pickle import TRUE
from django.db import models
from django.utils import timezone
from tshirt.models import Tshirt
from payment.models import Payment



class Sale(models.Model):
    createdAt = models.DateTimeField(default=timezone.now)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)
    status = models.IntegerField()

src/tshirt/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


class Size(models.Model):
  name = models.CharField(max_length=30)
  measure = ArrayField(
      models.FloatField(default=0),
      size=3,)

class Tshirt(models.Model):
  name = models.CharField(max_length=30, blank=False)
  description = models.TextField(
      max_length=100, blank=True)  # not sure is needed
  color = models.CharField(max_length=30, blank=False)
  price = models.FloatField(blank=False, default=0.00)
  qtyInStock = models.IntegerField(default=1)
  photo = models.ImageField(upload_to='tshirt/static/img/tshirts/', null=True)
  position = ArrayField(models.IntegerField(default=0), size=2, null=True)
  size = models.ForeignKey(Size, null=True, on_delete=models.CASCADE)

  class Gender(models.IntegerChoices):
    MALE = 0
    FEMALE = 1
    UNISEX = 2
  
  gender = models.IntegerField(choices=Gender.choices, blank=False)

  @property
  def photo_url(self):
    if self.photo and hasattr(self.photo, 'url'):
        return self.photo.url

src/payment/views.py
import os.path
from django.shortcuts import render
from payment.models import Payment
from tshirt.models import Tshirt
from pixqrcode import PixQrCode


def payment(request, id):
  tshirt = Tshirt.objects.get(id=id)
  payment = Payment.objects.create()
  name = "Martha Dantas Silva"
  mobile = "61991302532"
  city = "Brasília"
  amount = str(tshirt.price)
  pix = PixQrCode(name, mobile, city, amount)
  if os.path.isfile(f"/ img/pix.png"):
    path = f"/img/pix.png"
  else:
    pix.save_qrcode("/vendingmachine/src/payment/static/img",
                  f"pix")
    path = f"/img/pix.png"

  context = {"path": path, "tshirt": tshirt}
  return render(request, 'pix-payment.jinja2', context)

src/sale/views.py
from django.shortcuts import render

# Create your views here.

src/tshirt/views.py
from django.shortcuts import render
from tshirt.models import Tshirt
from django.core.paginator import Paginator


def index(request, page=1):
  tshirts = Tshirt.objects.all()

  paginator = Paginator(tshirts, per_page=9)
  tshirt = paginator.get_page(page)
  context = {"tshirts": tshirt.object_list, "page_obj": tshirt}
  
  return render(request, 'index.jinja2', context)

def selectedTshirt(request, id):
  tshirt = Tshirt.objects.get(id=id)

  tshirts = list(Tshirt.objects.filter(name=tshirt.name).order_by('size'))
  
  context = {"tshirts": tshirts, "tshirt": tshirt}

  return render(request, 'selected-tshirt.jinja2', context)

src/payment/templates/pix-payment.jinja2
{% load static %}
<html>
  <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'tshirts/pix-payment.css' %}">
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="return">
      <a href="{% url 'selectedTshirt' tshirt.id %}"> 
        <button class=" btn btn-return"> 
          <i class="fa fa-arrow-left action fa-xxg" aria-hidden="true"></i>
        </button>
      </a>
    </div>
    <div class="pix-qrcode">
      <img src="{% static path %}">
      <h2 class="info">ESCANEIE O QRCODE ACIMA</h2>
    </div>
    <div class="sale-details">
      <span>Resumo da compra:</span>
      <span class="tshirt-name">{{tshirt.name}}</span>
      <span class="tshirt-price">R$ {{tshirt.price}}0</span>
    </div>
    <div class="cancel">
      <a href="{% url 'tshirt' %}"> 
        <button class="btn btn-info">CANCELAR</button>
      </a>
    </div>
  </body>
</html>

src/tshirt/templates/index.jinja2
{% load static %}
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'tshirts/index.css' %}">
  <script src="https://kit.fontawesome.com/f9680fb690.js" crossorigin="anonymous"></script>
  </head>
<body>
  <section class="list-tshirts">
    <div class="container">
      <div class="w3-row">
        <div class="col-lg-8">
          <div class="row">
          {% for tshirt in tshirts %}
            <div class="card-div col-lg-4 col-md-4 col-sm-4">
              <div class="product-item">
                <a href="{% url 'selectedTshirt' tshirt.id %}">
                  <div class="card">
                    <img class="card-img-top" src="{{ tshirt.photo_url|default_if_none:'#'}}" alt="Card image cap">
                    <div class="product-info">
                      <div class="product-name item">
                        <span>
                          {{ tshirt.name }}
                        </span>
                      </div>
                      <div class="product-price item">
                        <span>
                          R$ {{ tshirt.price }}
                        </span>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          {% endfor%}
          </div>
          <div class="row col col-lg-12 product-pagination" style="display:flex; justify-content:space-between">
            {%if page_obj.has_previous%}
                <a href="/tshirt/{{page_obj.previous_page_number}}">
                  <i class=" col-2 fa fa-thin fa-arrow-left" style="color: #42C5BD; font-size:60px;">
                  </i>
                </a>
              {% else %}
                <div class="col-2"></div>
            {%endif%}
            <div style="justify-content:center; font-size:25px; text-align:center;">
                {% for page_number in page_obj.paginator.page_range %}
                  <a href="{% url 'tshirts' page_number %}">
                    <div class="pageMarker {% if page_number == page_obj.number %}pageCurrent{% endif %}"> </div>
                  </a>
                {% endfor %}
            </div>
              {%if page_obj.has_next%}
                <a href="/tshirt/{{page_obj.next_page_number}}">
                  <i class="col-2 fa fa-thin fa-arrow-right" style="color: #42C5BD; text-align:center; font-size:60px;">
                  </i>
                </a>
              {% else %}
                <div class="col-2"></div>
              {%endif%}
            </div>
            </div>
      </div>
    </div>
  </section>
</body>
</html>

src/tshirt/templates/selected-tshirt.jinja2
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'tshirts/selected.css' %}">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    </head>
    <body>
        <div class="bar-side lb bar-block card bg-lb">
            <h3 class=" font-weight-bold wc" style="padding-top: 80%"> Escolha o tamanho:</h3>


            <input type="radio" name="size-select" id="option-xp" value="xp" disabled>
            <input type="radio" name="size-select" id="option-p" value="p" disabled>
            <input onclick="window.location='{% url 'selectedTshirt' tshirts.1.id %}';" type="radio" name="size-select" id="option-m" value="m">
            <input onclick="window.location='{% url 'selectedTshirt' tshirts.0.id %}';" type="radio" name="size-select" id="option-g" value="g">
            <input type="radio" name="size-select" id="option-xg" value="xg" disabled>
            
            
            <label for="option-xp" class="bar-item bar-label" style="margin-top: -470!important" disabled>XP </label>
            <label for="option-p"  class="bar-item bar-label">P </label>
            <label for="option-m"  class="bar-item bar-label">M </label>
            <label for="option-g"  class="bar-item bar-label" disabled>G </label>
            <label for="option-xg" class="bar-item bar-label" disabled>XG</label>

            <h1 class="font-weight-bold wc" style="margin-top: 370px">
                Preço: R$ {{ tshirt.price }}
            </h1>
            <a href="{% url 'payments:payment' id=tshirt.id %}">
            <button class=" btn btn-buy bg-action" style="margin-top: 80px"> 
                <h1 class="font-weight-bold wc" >Comprar</h1>
            </button>
            </a>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="col-3">
                <a href="{% url 'tshirt' %}"> 
                    <button class=" btn btn-return"> 
                        <i class="fa fa-arrow-left action fa-xxg" aria-hidden="true"></i>
                    </button>
                </a>
            </div>
            <div class="col-2"> 
                <h2 class="font-weight-bold db">
                    {{ tshirt.name }}
                </h2>
            </div>
            <div class="col-7"></div>
        </nav>
        <div class="image-full">
            <img src="{{ tshirt.photo_url|default_if_none:'#' }}"/>
        </div>
        <div class="image-icon">
            <img src="{{ tshirt.photo_url|default_if_none:'#' }}"/>
        </div>
    </body>
</html>